Inside/InsideForum/Controllers/ReportController.cs
using System;
using System.Web.Mvc;
using InsideX.Helper;
using MyUtility.Extensions;
using PhuSaiThanhLib.Enum;

namespace InsideX.Controllers
{
    [AdminAuthorize]
    public class ReportController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WebsiteBuy()
        {
            return View();
        }

        public ActionResult WebsiteRent()
        {
            return View();
        }

        public ActionResult EmployeeReal()
        {
            return View();
        }

        public ActionResult EmployeeCustomer()
        {
            return View();
        }

        public ActionResult EmployeeRealSearch(DateTime? dateFrom, DateTime? dateTo, int employeeType = 1, int realBuyOrRent = 1)
        {
            dateFrom = dateFrom ?? DateTime.Now.AddYears(-1);
            dateTo = dateTo ?? DateTime.Now;
            dateFrom = new DateTime(dateFrom.Value.Year, dateFrom.Value.Month, dateFrom.Value.Day, 0, 0, 1);
            dateTo = new DateTime(dateTo.Value.Year, dateTo.Value.Month, dateTo.Value.Day, 23, 59, 59);


            var model = new EmployeeRealSearchParam {
                EmployeeType = employeeType,
                RealBuyOrRent = realBuyOrRent,
                DateFrom = dateFrom,
                DateTo = dateTo
            };

            if (employeeType == EmployeeTypeEnum.Real.Value()) {
                return PartialView("EmployeeRealSearch_Real", model);
            }
            else {
                return PartialView("EmployeeRealSearch_Customer", model);
            }

            return PartialView(string.Format("EmployeeRealSearch_{0}", employeeType.NumberToEnumToText<EmployeeTypeEnum>(), realBuyOrRent.NumberToEnumToText<RealBuyOrRentEnum>()), model);
            //if (employeeType == EmployeeTypeEnum.Real.Value()) {
            //    if (realBuyOrRent == RealBuyOrRentEnum.Buy.Value())
            //        return PartialView("EmployeeRealSearch_Real_Buy");
            //    else
            //        return PartialView("EmployeeRealSearch_Real_Rent");
            //}
            //else {
            //    return PartialView(string.Format("EmployeeRealSearch_{0}",employeeType.NumberToEnumToText<EmployeeTypeEnum>(),realBuyOrRent.NumberToEnumToText<RealBuyOrRentEnum>()));
            //}
            //return PartialView(string.Format("EmployeeRealSearch_{0}_{1}", employeeType.NumberToEnumToText<EmployeeTypeEnum>()));
        }
    }



    public class EmployeeRealSearchParam
    {
        public int EmployeeType { get; set; }
        public int RealBuyOrRent { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
    }
}

Inside/InsideForum/Views/Report/EmployeeReal.cshtml
@using InsideX.EF
@using InsideX.Helper
@using InsideX.Models
@using InsideX.Models.Customer
@using MyUtility.Extensions
@using PhuSaiThanhLib.Enum
@using PhuSaiThanhLib.Real
@using RealDirectionEnum = PhuSaiThanhLib.Enum.RealDirectionEnum
@{
    ViewBag.PageName = ViewBag.Title = "Thống kê theo nhân viên " ;

}
<div class="right_col" role="main">
    <div class="">
        <div class="">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Bộ lọc</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content form-horizontal">
                    <div class="">
                        <form id="preview_form" class="">
                            <div class="row ">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="EmployeeType" class="col-sm-4 control-label">Loại nhân viên</label>
                                        <div class="col-sm-8">
                                            @Html.DropDownList("EmployeeType", typeof(EmployeeTypeEnumDisplay2).ToList().ToSelectListItems(), new { @class = "form-control" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="RealBuyOrRent" class="col-sm-4 control-label">Loại bđs</label>
                                        <div class="col-sm-8">
                                            @Html.DropDownList("RealBuyOrRent", typeof(RealBuyOrRentEnum).ToList().ToSelectListItems(), new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="DateFrom" class="col-sm-4 control-label">Từ ngày</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control has-feedback-left" id="DateFrom" name="DateFrom" placeholder="năm-tháng-ngày" aria-describedby="inputSuccess2Status2" value="">
                                            <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="DateTo" class="col-sm-4 control-label">Đến ngày</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control has-feedback-left" id="DateTo" name="DateTo" placeholder="năm-tháng-ngày" aria-describedby="inputSuccess2Status2" value="">
                                            <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-6">
                                    <div class="form-group">
                                        <div class="col-sm-8">
                                            <button type="button" id="search" class="btn btn-primary">
                                                <span class="padding-left-20 padding-right-20">Tìm</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>


                </div>
            </div>
        </div>

        <div class="clearfix"></div>
      
        <div class="x_panel" id="ContainerData">
            <div class="x_content">
                <div id="resultContain">
                    
                </div>
                <div class="btn-toolbar bottom tableexport-caption">
                    <button class="btn btn-default xlsx" onclick="exportToExcel()">Export to xlsx</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section css
{
    <link href="~/Content/dataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/Content/select2-4.0.3/css/select2.min.css" rel="stylesheet" />
<link href="~/Content/Fullscreen-Lightbox/src/css/jquery.imageview.css" rel="stylesheet" />


}


@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Content/dataTables/js/jquery.dataTables.js"></script>
    
    <script>
        function search() {
            var model = {};
            var form = $("#preview_form").serializeArray();
            for (var i = 0; i < form.length; i++) {
                model[form[i].name] = form[i].value;
            }

            $.post('@Url.Action("EmployeeRealSearch","Report")', model, function(result) {
                $("#resultContain").html(result);
            });

        }


        $(document).ready(function() {

            $('#DateFrom').daterangepicker({
                singleDatePicker: true,
                timePicker: false,
                timePicker24Hour: false,
                //timePickerIncrement: 10,
                locale: {
                    format: 'YYYY-MM-DD'
                }
            });

            $('#DateTo').daterangepicker({
                singleDatePicker: true,
                timePicker: false,
                timePicker24Hour: false,
                //timePickerIncrement: 10,
                locale: {
                    format: 'YYYY-MM-DD'
                }
            });

            $('#DateFrom').val('');
            $('#DateTo').val('');

            $("#search").click(function() {
                search();
            });
        })
    </script>
}

Inside/InsideForum/Views/Report/EmployeeRealSearch_Customer.cshtml
@using InsideX.EF
@using InsideX.Models.Customer
@using MyUtility.Extensions
@using PhuSaiThanhLib.Enum
@using PhuSaiThanhLib.Real
@model InsideX.Controllers.EmployeeRealSearchParam

@{
    var db = new PstEntities();

    var emps = db.Employees.Where(c => c.Type == Model.EmployeeType && c.Role == 3).OrderBy(c => c.DisplayName);
    //var reals = db.Reals.Where(c => c.BuyOrRent == Model.RealBuyOrRent).ToList();
    var cuss = db.Customers.Where(c => c.Type == Model.RealBuyOrRent).ToList();
    var statusBuy = typeof(CustomerType2Enum).ToList();


}


<table class="table table-bordered">
    <thead>
        <tr class="text-align-center">
            <th>#Id</th>
            <th>Tên</th>
            <th class="text-align-right">Tạo mới</th>
            <th class="text-align-right">Cập nhật</th>
            @foreach (var s in statusBuy) {
                <th class="text-align-right">@(s.Value)</th>
            }
            <th class="text-align-right">Hổ trợ</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in emps) {
            <tr>
                <td>@employee.ID</td>
                <td>@(employee.DisplayName)(@employee.Username)</td>
                <td class="text-align-right">@cuss.Count(c => c.BrokerId == employee.ID && c.CreatedDate > Model.DateFrom && c.CreatedDate < Model.DateTo)</td>
                <td class="text-align-right">@cuss.Count(c => c.BrokerId == employee.ID && c.UpdatedDate > Model.DateFrom && c.UpdatedDate < Model.DateTo)</td>
                @foreach (var s in statusBuy) {
                    <td class="text-align-right">@cuss.Count(c => c.BrokerId == employee.ID && c.CreatedDate > Model.DateFrom && c.CreatedDate < Model.DateTo && (c.Type2 ?? 0) == s.Key)</td>
                }
                <td class="text-align-right">@db.Ins_CustomerCare_Count(employee.BrokerId,Model.DateFrom,Model.DateTo).Count()</td>
            </tr>
        }
    </tbody>
</table>

Inside/InsideForum/Views/Report/EmployeeRealSearch_Real.cshtml
@using InsideX.EF
@using MyUtility.Extensions
@using PhuSaiThanhLib.Enum
@using PhuSaiThanhLib.Real
@model InsideX.Controllers.EmployeeRealSearchParam

@{
    var db = new PstEntities();

    var emps = db.Employees.Where(c => c.Type == Model.EmployeeType && c.Role == 3).OrderBy(c => c.DisplayName);
    var reals = db.Reals.Where(c => c.BuyOrRent == Model.RealBuyOrRent).ToList();
    var statusBuy = new List<int> { 1, 2, 5, 6, 7 };
    if (Model.RealBuyOrRent == RealBuyOrRentEnum.Rent.Value()) {
        statusBuy = new List<int> { 4, 3, 5, 6, 8 };
    }

}


<table class="table table-bordered">
    <thead>
        <tr class="text-align-center">
            <th>#Id</th>
            <th>Tên</th>
            <th class="text-align-right">Tạo mới</th>
            <th class="text-align-right">Cập nhật</th>
            @foreach (var s in statusBuy) {
                <th class="text-align-right">@(s.NumberToEnumToText<RealStatusEnum>())</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in emps) {
            <tr>
                <td>@employee.ID</td>
                <td>@(employee.DisplayName)(@employee.Username)</td>
                <td class="text-align-right">@reals.Count(c => c.BrokerId == employee.ID && c.CreatedDate > Model.DateFrom && c.CreatedDate < Model.DateTo)</td>
                <td class="text-align-right">@reals.Count(c => c.BrokerId == employee.ID && c.UpdatedDate > Model.DateFrom && c.UpdatedDate < Model.DateTo)</td>
                @foreach (var s in statusBuy) {
                    <td class="text-align-right">@reals.Count(c => c.BrokerId == employee.ID && c.CreatedDate > Model.DateFrom && c.CreatedDate < Model.DateTo && c.Status == s)</td>
                }
            </tr>
        }
    </tbody>
</table>

Inside/InsideForum/Views/Report/Index.cshtml
@using InsideX.EF
@using MyUtility.Extensions
@using PhuSaiThanhLib.Enum
@using PhuSaiThanhLib.Real

@{
    ViewBag.PageName = ViewBag.Title = "Báo cáo thống kê ";
    var db = new PstEntities();
    var real = db.Reals;


}

<div class="right_col" role="main">
    <div class="x_panel">
        <div class="x_title">
            <h2>Thống kê theo trạng thái</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="row">
                @{
                    var statusBuy = new List<int> { 1, 2, 5, 6, 7 };
                    var statusRent = new List<int> { 4, 3, 5, 6, 8 };
                }
                <div class="col-lg-6">
                    <label>Bđs bán</label>
                    @foreach (var item in statusBuy) {
                        <div>@(item.NumberToEnumToText<RealStatusEnum>()) : @real.Count(c => c.Status == item && c.BuyOrRent == 1)</div>
                    }
                </div>

                <div class="col-lg-6">
                    <label>Bđs cho thuê</label>
                    @foreach (var item in statusRent) {
                        <div>@(item.NumberToEnumToText<RealStatusEnum>()) : @real.Count(c => c.Status == item && c.BuyOrRent == 2)</div>
                    }
                </div>
            </div>

        </div>
    </div>

    <div class="x_panel">
        <div class="x_title">
            <h2>Thống kê theo loại</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="row">
                @{
                    var type = typeof(RealTypeEnum).ToList();
                }
                <div class="col-lg-6">
                    <label>Bđs bán</label>
                    @foreach (var item in type) {
                        <div>@(item.Key.NumberToEnumToText<RealTypeEnum>()) : @real.Count(c => c.Type == item.Key && c.BuyOrRent == 1)</div>
                    }
                </div>

                <div class="col-lg-6">
                    <label>Bđs cho thuê</label>
                    @foreach (var item in type) {
                        <div>@(item.Key.NumberToEnumToText<RealTypeEnum>()) : @real.Count(c => c.Type == item.Key && c.BuyOrRent == 2)</div>
                    }
                </div>
            </div>

        </div>
    </div>

</div>

Inside/InsideForum/Views/Report/WebsiteBuy.cshtml
@using InsideX.EF
@using MyUtility.Extensions
@using PhuSaiThanhLib.Real

@{
    ViewBag.PageName = ViewBag.Title = "Website bán ";
    var db = new PstEntities();
    var real = db.Reals.Where(c => c.BuyOrRent == 1).ToList();


}

<div class="right_col" role="main">
    <div class="row">
        <div class="col-lg-4">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Thống kê theo trạng thái</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @{
                        var statusBuy = new List<int> { 1, 2, 5, 6, 7 };
                    }
                    <label>Bđs bán</label>
                    @foreach (var item in statusBuy) {
                        <div>@(item.NumberToEnumToText<RealStatusEnum>()) : @real.Count(c => c.Status == item)</div>
                    }
                    <div>Giá tốt : @real.Count(c => c.IsPriceHot == true)</div>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <div class="col-lg-4">

            <div class="x_panel">
                <div class="x_title">
                    <h2>Thống kê theo loại</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @{
                        var type = typeof(RealTypeEnum).ToList();
                    }
                    <label>Bđs bán</label>
                    @foreach (var item in type) {
                    <div>@(item.Key.NumberToEnumToText<RealTypeEnum>()) : @real.Count(c => c.Type == item.Key)</div>
                    }

                </div>
            </div>
        </div>

        <div class="col-lg-4">

            <div class="x_panel">
                <div class="x_title">
                    <h2>Thống kê theo giá</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @{
                        var range = new List<List<decimal>>
                        {
                            new List<decimal> {0,1},
                            new List<decimal> {1,2},
                            new List<decimal> {2,3},
                            new List<decimal> {3,4},
                            new List<decimal> {4,5},
                            new List<decimal> {5,6},
                            new List<decimal> {6,7},
                        };

                    }
                    <label>Bđs bán</label>
                    @foreach (var item in range) {
                        <div>@item[0] ~ @item[1] (tỷ) : @real.Count(c => c.Price > item[0] && c.Price <= item[1])</div>
                    }
                    <div> > @range.Last()[1] (tỷ) : @real.Count(c => c.Price > range.Last()[1])</div>


                </div>
            </div>
        </div>
    </div>

    <div class="x_panel">
        <div class="x_title">
            <h2>Thống kê theo quận</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div>
                <!-- Nav tabs -->
                @{
                    var districts = db.MyDistricts.ToList();
                    int i = 0;
                }
                <ul class="nav nav-tabs" role="tablist">
                    @foreach (var district in districts)
                    {
                        var dCount = real.Count(c => c.DistrictId == district.Id);
                        if (dCount > 0)
                        {
                            <li role="presentation" class="@(i == 0 ? "active" : "")">
                                <a href="#district@(district.Id)" aria-controls="district" role="tab" data-toggle="tab">@district.DistrictName (@dCount)</a>
                            </li>
                        
                            i++;
                        }
                       
                    }
                </ul>
                @{
                    i = 0;
                }
                <!-- Tab panes -->
                <div class="tab-content">
                    
                    @foreach (var district in districts)
                    {
                        var dCount = real.Count(c => c.DistrictId == district.Id);
                        if (dCount > 0)
                        {
                            <div role="tabpanel" class="tab-pane @(i == 0 ? "active" : "")" id="district@(district.Id)">
                                <br />

                                @{
                                    var wards = db.MyWards.Where(c => c.DistrictId == district.Id).ToList();
                                    var streets = db.MyStreets.Where(c => c.DistrictId == district.Id).OrderBy(c => c.StreetName).ToList();

                                }
                                <div class="row">
                                    <div class="col-lg-6">

                                        <table class="table table-bordered">
                                            <tr>
                                                <th>Phường</th>
                                                <th>Đang bán</th>
                                                <th>Tất cả</th>
                                            </tr>
                                            @foreach (var ward in wards)
                                            {
                                                var w1 = real.Count(c => c.WardId == ward.Id && c.Status == 1);
                                                var w2 = real.Count(c => c.WardId == ward.Id);
                                                if (w1 > 0 || w2 > 0)
                                                {

                                                    <tr>
                                                        <td>@ward.WardName</td>
                                                        <td>@w1</td>
                                                        <td>@w2</td>
                                                    </tr>
                                                }
                                            }
                                        </table>

                                    </div>
                                    <div class="col-lg-6">
                                        <table class="table table-bordered">
                                            <tr>
                                                <th>Đường</th>
                                                <th>Đang bán</th>
                                                <th>Tất cả</th>
                                            </tr>
                                            @foreach (var street in streets)
                                            {
                                                var s1 = real.Count(c => c.StreetId == street.Id && c.Status == 1);
                                                var s2 = real.Count(c => c.StreetId == street.Id);
                                                if (s1 > 0 || s2 > 0)
                                                {
                                                    <tr>
                                                        <td>@street.StreetName</td>
                                                        <td>@s1</td>
                                                        <td>@s2</td>
                                                    </tr>
                                                }
                                            }
                                        </table>
                                    </div>
                                </div>

                            </div>
                            i++;
                        }
                    }

                </div>

            </div>

        </div>
    </div>


</div>

Inside/InsideForum/Views/Report/WebsiteRent.cshtml
@using InsideX.EF
@using MyUtility.Extensions
@using PhuSaiThanhLib.Enum
@using PhuSaiThanhLib.Real

@{
    ViewBag.PageName = ViewBag.Title = "Website thuê ";
    var db = new PstEntities();
    var real = db.Reals.Where(c => c.BuyOrRent == 2).ToList();


}

<div class="right_col" role="main">
    <div class="row">
        <div class="col-lg-4">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Thống kê theo trạng thái</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @{
                        var statusRent = new List<int> { 4, 3, 5, 6, 8 };
                    }


                    <div class="col-lg-6">
                        <label>Bđs cho thuê</label>
                        @foreach (var item in statusRent) {
                            <div>@(item.NumberToEnumToText<RealStatusEnum>()) : @real.Count(c => c.Status == item && c.BuyOrRent == 2)</div>
                        }
                        <div>Giá tốt : @real.Count(c => c.IsPriceHot == true)</div>
                    </div>
                    <br />
                    <br />
                </div>
            </div>
        </div>
        <div class="col-lg-4">

            <div class="x_panel">
                <div class="x_title">
                    <h2>Thống kê theo loại</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @{
                        var type = typeof(RealTypeEnum).ToList();
                    }


                    <div class="col-lg-6">
                        <label>Bđs cho thuê</label>
                        @foreach (var item in type) {
                            <div>@(item.Key.NumberToEnumToText<RealTypeEnum>()) : @real.Count(c => c.Type == item.Key && c.BuyOrRent == 2)</div>
                        }
                    </div>

                </div>
            </div>
        </div>
        <div class="col-lg-4">

            <div class="x_panel">
                <div class="x_title">
                    <h2>Thống kê theo giá</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    @{
                        var range = new List<List<decimal>>
                        {
                            new List<decimal> {0,1},
                            new List<decimal> {1,2},
                            new List<decimal> {2,3},
                            new List<decimal> {3,4},
                            new List<decimal> {4,5},
                            new List<decimal> {5,6},
                            new List<decimal> {6,7},
                        };

                    }
                    <label>Bđs bán</label>
                    @foreach (var item in range) {
                        <div>@item[0] ~ @item[1] (triệu) : @real.Count(c => c.Price > item[0] && c.Price <= item[1])</div>
                    }
                    <div> > @range.Last()[1] (triệu) : @real.Count(c => c.Price > range.Last()[1])</div>


                </div>
            </div>
        </div>
    </div>

    <div class="x_panel">
        <div class="x_title">
            <h2>Thống kê theo quận</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div>
                <!-- Nav tabs -->
                @{
                    var districts = db.MyDistricts.ToList();
                    int i = 0;
                }
                <ul class="nav nav-tabs" role="tablist">
                    @foreach (var district in districts) {
                        var dCount = real.Count(c => c.DistrictId == district.Id);
                        if (dCount > 0) {
                            <li role="presentation" class="@(i == 0 ? "active" : "")">
                                <a href="#district@(district.Id)" aria-controls="district" role="tab" data-toggle="tab">@district.DistrictName (@dCount)</a>
                            </li>
                            i++;
                        }

                    }
                </ul>
                @{
                    i = 0;
                }
                <!-- Tab panes -->
                <div class="tab-content">
                    <br />
                    @foreach (var district in districts) {
                        <div role="tabpanel" class="tab-pane @(i == 0 ? "active" : "")" id="district@(district.Id)">
                            @*@district.DistrictName*@
                            @{
                        var wards = db.MyWards.Where(c => c.DistrictId == district.Id).ToList();
                        var streets = db.MyStreets.Where(c => c.DistrictId == district.Id).OrderBy(c => c.StreetName).ToList();

                            }
                            <div class="row">
                                <div class="col-lg-6">

                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Phường</th>
                                            <th>Đang cho thuê</th>
                                            <th>Tất cả</th>
                                        </tr>
                                        @foreach (var ward in wards) {
                                            <tr>
                                                <td>@ward.WardName</td>
                                                <td>@real.Count(c => c.WardId == ward.Id && c.Status == 4)</td>
                                                <td>@real.Count(c => c.WardId == ward.Id)</td>
                                            </tr>
                                        }
                                    </table>

                                </div>
                                <div class="col-lg-6">
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Đường</th>
                                            <th>Đang cho thuê</th>
                                            <th>Tất cả</th>
                                        </tr>
                                        @foreach (var street in streets) {
                                            <tr>
                                                <td>@street.StreetName</td>
                                                <td>@real.Count(c => c.StreetId == street.Id && c.Status == 1)</td>
                                                <td>@real.Count(c => c.StreetId == street.Id)</td>
                                            </tr>
                                        }
                                    </table>
                                </div>
                            </div>

                        </div>
                                        i++;
                    }

                </div>

            </div>

        </div>
    </div>


</div>