OutsideX/Controllers/ApiController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BussinessObject;
using EntitiesObject.Entities.WebEntities;
using MyConfig;
using MyUtility.Extensions;
using OutsideX.Models;
using PhuSaiThanhLib.Enum;

namespace OutsideX.Controllers
{
    public class ApiController : Controller
    {
        /// <summary>
        /// tab = 0 nha dat gia tot,1 cho thue gia tot,2 nha dat da ban
        /// </summary>
        /// <param name="tabName"></param>
        /// <param name="tab"></param>
        /// <param name="pageSize"></param>
        /// <param name="pageIndex"></param>
        /// <param name="priceType"></param>
        /// <returns></returns>
        public ActionResult HomeBds(string tabName, int tab = 1, int pageSize = 10, int pageIndex = 1, int priceType = 1)
        {
            pageSize = MyConfiguration.Default.PageSize;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = tab == 3 ? 0 : tab,
                SortType = priceType,
            };

            var total = 0;
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            return PartialView(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tabName"></param>
        /// <param name="tab">tab: 1 & 2</param>
        /// <param name="pageIndex"></param>
        /// <param name="priceType">1: giam dan; 2: tang dan</param>
        /// <returns></returns>
        public ActionResult NhaDatBan(string tabName, int tab = 1, int pageSize = 10, int pageIndex = 1, int priceType = 1, bool isHot = false)
        {
            pageSize = MyConfiguration.Default.PageSize;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = 1,
                RealStatus = 0,
                SortType = priceType,
                IsHotPrice = isHot,
            };
            switch (tab) {
                case 2:
                    request.RealStatus = 2;
                    break;
                case 3:
                    request.RealStatus = 7;
                    break;
                default:
                    request.RealStatus = 0;
                    break;
            }


            var total = 0;
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            return PartialView("HomeBds", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="tabName"></param>
        /// <param name="tab">tab: 1 & 2</param>
        /// <param name="pageIndex"></param>
        /// <param name="priceType">1: giam dan; 2: tang dan</param>
        /// <returns></returns>
        public ActionResult NhaDatChoThue(string tabName, int tab = 1, int pageSize = 10, int pageIndex = 1, int priceType = 1)
        {
            pageSize = MyConfiguration.Default.PageSize;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = 2,
                RealStatus = 0,
                SortType = priceType,
            };
            switch (tab) {
                case 2:
                    request.RealStatus = 2;
                    break;
                case 3:
                    request.RealStatus = 7;
                    break;
                default:
                    request.RealStatus = 0;
                    break;
            }
            var total = 0;
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            return PartialView("HomeBds", model);
        }
        public ActionResult NhaDatTuongTu(RealBuyOrRentEnum saleOrRent, string tabName, int tab = 1, int pageSize = 10, int pageIndex = 1, int priceType = 1, int wardId = 0, double price = 0)
        {
            pageSize = MyConfiguration.Default.PageSize;

            var min = price - 0.5;
            if (min < 0)
                min = 0;
            var max = price + 0.5;

            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = saleOrRent.Value(),
                RealStatus = tab == 2 ? 3 : 0,
                SortType = priceType,
                MinPrice = (decimal)min,
                MaxPrice = (decimal)max,
                WardId = wardId,

            };
            var total = 0;
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            return PartialView("HomeBds", model);
        }

        public ActionResult GetDistrict(int id = 0)
        {
            if (id == 0)
                return PartialView(new List<Xdistrict>());

            var model = BoFactory.AddressBook.GetDistrictByCity(id) ?? new List<Xdistrict>();
            return PartialView(model);
        }
        public ActionResult GetWard(int id = 0)
        {
            if (id == 0)
                return PartialView(new List<Xward>());

            var model = BoFactory.AddressBook.GetWardByDistrict(id) ?? new List<Xward>();
            return PartialView(model);
        }
        public ActionResult GetStreet(int id = 0)
        {
            if (id == 0)
                return PartialView(new List<Xstreet>());

            //var model = BoFactory.AddressBook.GetStreetByWard(id) ?? new List<Xstreet>();
            var model = BoFactory.AddressBook.GetStreetByDistrict(id) ?? new List<Xstreet>();
            return PartialView(model);
        }


    }
}

OutsideX/Controllers/RealEstateController.cs
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using BussinessObject;
using MyConfig;
using MyUtility.Extensions;
using OutsideX.EF;
using OutsideX.Models;
using PhuSaiThanhLib.Enum;
using WebUtility;

namespace OutsideX.Controllers
{
    public class RealEstateController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NhaDatBan()
        {
            ViewBag.NavBar = "NhaDatBan";
            var pageSize = MyConfiguration.Default.PageSize;
            const int pageIndex = 1;

            int total = 0;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = RealBuyOrRentEnum.Buy.Value()
            };
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            return View(model);
        }

        public ActionResult NhaDatChoThue()
        {
            ViewBag.NavBar = "NhaDatChoThue";
            var pageSize = MyConfiguration.Default.PageSize;
            const int pageIndex = 1;

            int total = 0;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = RealBuyOrRentEnum.Rent.Value()
            };
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            return View(model);
        }

        public ActionResult NhaDatTuongTu(RealBuyOrRentEnum saleOrRent, int wardId = 0, double price = 0)
        {
            ViewBag.NavBar = "NhaDatTuongTu";
            var pageSize = MyConfiguration.Default.PageSize;
            const int pageIndex = 1;
            var min = price - 0.5;
            if (min < 0)
                min = 0;
            var max = price + 0.5;

            int total = 0;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = saleOrRent.Value(),
                MinPrice = (decimal)min,
                MaxPrice = (decimal)max,
                SortType = DropdownSortTypeEnum.MoiNhat.Value(),
                WardId = wardId
            };
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            ViewBag.WardId = wardId;
            ViewBag.Price = price;
            ViewBag.saleOrRent = saleOrRent;
            return View(model);
        }

        public ActionResult CanMuaCanThue()
        {
            ViewBag.NavBar = "CanMuaCanThue";
            return View();
        }

        public ActionResult NhaDatGiaTot()
        {

            ViewBag.NavBar = "NhaDatChoThue";
            var pageSize = MyConfiguration.Default.PageSize;
            const int pageIndex = 1;

            int total = 0;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = RealBuyOrRentEnum.Buy.Value(),
                IsHotPrice = true

            };
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            ViewBag.NavBar = "GiaTot";
            return View(model);
        }

        public ActionResult ChoThueGiaTot()
        {

            ViewBag.NavBar = "NhaDatChoThue";
            var pageSize = MyConfiguration.Default.PageSize;
            const int pageIndex = 1;

            int total = 0;
            var request = new RealSearchModel {
                PageIndex = pageIndex,
                PageSize = pageSize,
                BuyOrRent = RealBuyOrRentEnum.Rent.Value(),
                IsHotPrice = true

            };
            var model = PstHelper.Real_Search(request, ref total);
            ViewBag.Total = total;
            ViewBag.PageSize = pageSize;
            ViewBag.PageIndex = pageIndex;
            ViewBag.NavBar = "GiaTot";
            return View(model);
        }


        public ActionResult DetailCustomer(int id = 0)
        {
            var db = new PstEntities();
            var real = db.Reals.FirstOrDefault(c => c.Id == id);
            if (real != null) {
                real.ViewCount = (real.ViewCount ?? 0) + 1;
                db.SaveChanges();
            }

            var model = db.Out_Real_Get_By_Id(id).FirstOrDefault();
            if (model == null)
                return RedirectToAction("NhaDatBan");

            var coo = CookieHelper.Get("Recent1");
            if (string.IsNullOrEmpty(coo))
                coo = id.ToString();
            else {
                var list = coo.Split(',').Take(20).ToList();
                //ViewBag.Recent = db.Out_Real_RecentViewed(string.Join(";", list.Where(c => c != id.ToString()))).ToList();
                ViewBag.Recent = PstHelper.Real_Search(new RealSearchModel {
                    PageIndex = 1,
                    PageSize = 20,
                    BuyOrRent = model.BuyOrRent,
                    SortType = DropdownSortTypeEnum.MoiNhat.Value(),
                    Title = string.Join("#", list.Where(c => c != id.ToString()))
                });


                list.Insert(0, id.ToString());
                coo = string.Join(",", list.Distinct().Take(20));
            }
            CookieHelper.Add("Recent1", coo);

            var m = new decimal(0.5);

            ViewBag.Similar = PstHelper.Real_Search(new RealSearchModel {
                PageIndex = 1,
                PageSize = 20,
                BuyOrRent = model.BuyOrRent,
                MinPrice = (model.Price ?? 0) - m,
                MaxPrice = (model.Price ?? 0) + m,
                SortType = DropdownSortTypeEnum.MoiNhat.Value(),
                WardId = model.WardId
            });


            
            ViewBag.NavBar = "DetailCustomer";
            ViewBag.SaleOrRent = model.BuyOrRent;
            ViewBag.Price = model.Price;
            ViewBag.WardId = model.WardId;
            return View("DetailCustomer", model);
        }

        //public ActionResult DetailStaff()
        //{
        //    ViewBag.NavBar = "DetailStaff";
        //    return View();
        //}
    }
}

OutsideX/Views/RealEstate/CanMuaCanThue.cshtml
@{
    ViewBag.Title = "Nhà Đất Bán";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<div class="div_breadcrumb">
    Phú Sài Thành<span class="glyphicon glyphicon-menu-right"></span> Mua bán nhà đất <span class="glyphicon glyphicon-menu-right"></span> TP.HCM <span class="glyphicon glyphicon-menu-right"></span> Quận 6
</div>

<div class="row">
    <div class="div_center col-md-9">
        @{Html.RenderAction("BoxGiaTot", "Layout");}

        <div class="tab_box margin-top-20">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#muabannhadat" aria-controls="muabannhadat" role="tab" data-toggle="tab">NHÀ ĐẤT GIÁ TỐT</a></li>
                <li role="presentation"><a href="#muabannhadat" aria-controls="chothuegiatot" role="tab" data-toggle="tab">CHO THUÊ GIÁ TỐT</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab_box_ddl">
                    <div class="dropdown">
                        <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Bất động sản nổi bật
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li><a href="#">Giá giảm dần</a></li>
                            <li><a href="#">Giá tăng dần</a></li>
                            <!--<li role="separator" class="divider"></li>-->
                        </ul>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane active padding-top-15" id="muabannhadat">
                    
                    @*<div class="list_item ">

                        @for (int i = 0; i < 5; i++)
                        {
                            <div class="item_box item_type_2 background-color-white margin-top-15">
                                <div class="row margin-0">
                                    <div class="col-sm-3 item_img padding-10">
                                        <a href="@Url.Action("DetailCustomer", "RealEstate")">
                                            <img src="~/Content/img/ex_home.jpg" class="img-responsive block-center" />
                                        </a>
                                    </div>
                                    <div class="col-sm-9 item_content">
                                        <div class="item_name">
                                            <div class="item_price"><span class="color-ed1c24"><span class="font-size-22"><strong>1,2 </strong></span><span class="font-size-14">tỷ</span></span></div>
                                            <a href="@Url.Action("DetailCustomer", "RealEstate")" class="item_link_hover is_hot_@(item.IsHot.ToString().ToLower()) ">
                                                Nhà đất mặt tiền, lầu 1 đường tân hóa quận @i giấy tờ đầy đủ, chính chủ, miễn trung gian
                                            </a>
                                        </div>
                                        <div class="address">Phạm Đình Hổ, Phường 11, Quận 6, TP.HCM</div>
                                        <div class="row">
                                            <div class="col-md-3">
                                                <strong>Căn Hộ</strong>
                                                <br />
                                                <strong>Hướng: </strong> Đông bắc
                                            </div>
                                            <div class="col-md-3">
                                                <strong>Mặt tiền</strong>
                                                <br />
                                                <strong>Kinh doanh</strong>
                                            </div>
                                            <div class="col-md-3">
                                                <strong>Diện tích:</strong> 120m2
                                                <br />
                                                <strong>DTSD:</strong> 240m2
                                            </div>
                                            <div class="col-md-3">
                                                <div class="item_tg">
                                                    <span>37 phút trước </span>
                                                    <br /><span class="item_eye">357</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        }
                    </div>*@
                </div>
                <div role="tabpanel" class="tab-pane" id="chothuenhadat">B</div>
                <div role="tabpanel" class="tab-pane" id="nhadatdaban">B</div>
            </div>


        </div>

        <div class="paging_type1 text-align-right">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    <li class="dropdown">
                        <span class="dropdown">
                            <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Trang 1/20
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dLabel">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Cuối</a></li>
                            </ul>
                        </span>

                    </li>
                    <li class="active"><span href="#">1</span></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true"><img src="~/Content/img/r-icon.png" /></span>
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="clearfix"></div>

        </div>
    </div>
    <div class="div_right col-md-3 ">

        @Html.Partial("RightBox/_DangTin")
        <div class="padding-top-5"></div>
        @{Html.RenderAction("RightBoxPhuong", "Layout");}
        <div class="padding-top-5"></div>
        @{Html.RenderAction("RightBoxXemNhieu", "Layout");}
        <div class="padding-top-5"></div>
        @{Html.RenderAction("RightBoxTinTuc", "Layout");}
    </div>
</div>

OutsideX/Views/RealEstate/ChoThueGiaTot.cshtml
@using MyUtility.Extensions
@using OutsideX.Models
@model List<OutsideX.EF.Out_Real_Search_Result>
@{
    ViewBag.Title = "Nhà Đất Bán";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
@*<div class="div_breadcrumb">
        Phú Sài Thành<span class="glyphicon glyphicon-menu-right"></span> Mua bán nhà đất <span class="glyphicon glyphicon-menu-right"></span> TP.HCM <span class="glyphicon glyphicon-menu-right"></span> Quận 6
    </div>*@

<div class="row">
    <div class="div_center col-md-9">
        @*@{Html.RenderAction("BoxGiaTot", "Layout");}*@

        <div class="tab_box margin-top-20">
            <ul class="nav nav-tabs" role="tablist" id="home_bds">
                <li role="presentation" class="active"><a href="#muabannhadat" aria-controls="muabannhadat" role="tab" data-toggle="tab">CHO THUÊ GIÁ TỐT</a></li>
                @*<li role="presentation"><a href="#chothuegiatot2" aria-controls="chothuegiatot2" role="tab" data-toggle="tab">CHO THUÊ NHÀ ĐẤT</a></li>*@
            </ul>
            <div class="tab-content">
                <div class="tab_box_ddl">
                    <div class="dropdown" id="ddl_type">
                        <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="ddl_name" value="">Bất động sản nổi bật</span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dLabel">
                            <li><a href="#" value="1">Giá giảm dần</a></li>
                            <li><a href="#" value="2">Giá tăng dần</a></li>
                            <!--<li role="separator" class="divider"></li>-->
                        </ul>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane active padding-top-15" id="muabannhadat">
                    <div class="amount_bds">Hiện có <span class="color-ed1c24">@ViewBag.Total</span> bất động sản</div>
                    @{ Html.RenderPartial("_ListHomeItem", Model);}


                    @*<div class="list_item">
                        @foreach (var item in Model)
                        {
                            <div class="item_box item_type_2 background-color-white margin-top-15">
                                <div class="row margin-0">
                                    <div class="col-sm-3 item_img padding-10">
                                        <a title="@item.ProductName" href="@Url.Action("DetailCustomer", "RealEstate", new { id = item.Id, productId = item.ProductId })" target="_blank">
                                            <img src="@item.ImgCover.GetFullUrlImage()" class="img-responsive block-center" onerror="CheckImg(this)" />
                                        </a>
                                    </div>
                                    <div class="col-sm-9 item_content">
                                        <div class="item_name">
                                            <div class="item_price">@Html.Raw(item.Price.DecimalToText("<span class='color-ed1c24'><span class='font-size-16'><strong>{0} </strong></span><span class='font-size-14'>{1}</span></span>"))</div>
                                            <a title="@item.ProductName" href="@Url.Action("DetailCustomer", "RealEstate", new { id = item.Id, productId = item.ProductId })" class="item_link_hover is_hot_@(item.IsHot.ToString().ToLower()) " target="_blank">
                                                @item.ProductName
                                            </a>
                                        </div>
                                        <div class="address">@string.Concat(@item.WardName, ", ", item.DistrictName, ", ", item.CityName)</div>
                                        <div class="row">
                                            <div class="col-md-3 col-xs-6">
                                                <strong>@(item.ProductType.GetValueOrDefault() == 0 ? "-------" : item.ProductType.GetValueOrDefault().ToEnum<RealTypeEnum>().Text())</strong>
                                                <br />
                                                <strong>Hướng: </strong> @item.ViewDirection.ToDirection()
                                            </div>
                                            <div class="col-md-3 col-xs-6">
                                                @switch (item.StreetType)
                                                {
                                                    case (int)RealStreetTypeEnum.MatTien:
                                                        <strong>Mặt tiền</strong>
                                                        <br />
                                                        <strong>Kinh doanh</strong>
                                                        break;
                                                    case (int)RealStreetTypeEnum.MatTienNoiBo:
                                                    <strong>Mặt tiền</strong>
                                                    <br />
                                                    <strong>Nội bộ</strong>
                                                        break;
                                                    case (int)RealStreetTypeEnum.HemTren5Met:
                                                    <strong>Hẻm</strong>
                                                    <br />
                                                    <strong>Trên 5 mét</strong>
                                                        break;
                                                    case (int)RealStreetTypeEnum.HemDuoi5Met:
                                                    <strong>Hẻm</strong>
                                                    <br />
                                                    <strong>Dưới 5 mét</strong>
                                                        break;
                                                }
                                            </div>
                                            <div class="col-md-3 col-xs-6">
                                                <strong>Diện tích:</strong> @item.SLand.ToDetault() m<sup>2</sup>
                                                <br />
                                                <strong>DTSD:</strong> @item.SContruction.ToDetault() m<sup>2</sup>
                                            </div>
                                            <div class="col-md-3 col-xs-6">
                                                <div class="item_tg">
                                                    <strong>Mã số: #</strong>@item.ProductId
                                                    <br /><span class="item_eye">@(item.ViewCount ?? 0)</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        }
                    </div>*@
                    <div class="padding-10"></div>
                    @Html.Partial("Paging/_HomePaging", new PagingModel(ViewBag.Total, ViewBag.PageSize, ViewBag.PageIndex))
                </div>
                <div role="tabpanel" class="tab-pane padding-top-15" id="chothuegiatot2"></div>
            </div>
        </div>
    </div>
    <div class="div_right col-md-3 ">

        @Html.Partial("RightBox/_DangTin")
        <div class="padding-top-5"></div>
        @{Html.RenderAction("RightBoxPhuong", "Layout");}
        <div class="padding-top-5"></div>
        @{Html.RenderAction("RightBoxXemNhieu", "Layout");}
        <div class="padding-top-5"></div>
        @{Html.RenderAction("RightBoxTinTuc", "Layout");}
    </div>
</div>

@section scripts
{
    <script>
        function getDataPage(pageIndex) {
            var tabName = $('#home_bds li.active a').attr("aria-controls");
            var tabId = 0;
            switch (tabName) {
                case "muabannhadat":
                    tabId = 1;
                    break;
                case "chothuegiatot2":
                    tabId = 2;
                    break;
                default:
                    tabId = 0;
                    break;
            }

            $.post('@Url.Action("NhaDatBan", "Api")', {
                pageIndex: pageIndex,
                pageSize: '@ViewBag.PageSize',
                tab: 2,
                tabName: tabName,
                isHot:true,
                priceType: $("#ddl_type .ddl_name").attr("value"),
            }, function (html) {
                $("#" + tabName).html(html);
            });
        }


        $(document).ready(function () {
            var tab1 = true;
            var tab2 = true;

            $('#home_bds a[data-toggle="tab"]').on("shown.bs.tab", function (e) {
                var id = e.target.getAttribute("aria-controls");
                switch (id) {
                    case "chothuegiatot2":
                        if (tab1) {
                            tab1 = false;
                            getDataPage(1);
                        }
                        break;
                    case "nhadatdaban":
                        if (tab2) {
                            tab2 = false;
                            getDataPage(1);
                        }
                        break;
                    default:
                        break;

                }
            });
            $(document).on("click", "#ddl_type li a", function (e) {
                e.preventDefault();
                $("#ddl_type .ddl_name").html($(this).html());
                $("#ddl_type .ddl_name").attr("value", $(this).attr("value"));
                getDataPage(1);
            });
        });
    </script>
}

OutsideX/Views/RealEstate/Index.cshtml
@{
    Layout = null;
}