OutsideX/Models/ContactToStaff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OutsideX.Models
{
    public class ContactToStaff
    {
        [Required(ErrorMessage = "Nhập họ tên.")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Nhập số điện thoại.")]
        public string Phone { get; set; }

        //[Required(ErrorMessage = "Nhập email.")]
        [EmailAddress(ErrorMessage = "Không đúng định dạng email.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Nhập nội dung.")]
        public string Content { get; set; }

        public int BrokerId { get; set; }

        public int RealId { get; set; }
    }
}

OutsideX/Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using BussinessObject;
using EntitiesObject.Entities.WebEntities;
using MyUtility.Extensions;
using OutsideX.EF;
using OutsideX.Models;
using PhuSaiThanhLib;
using PhuSaiThanhLib.Enum;

namespace OutsideX.Controllers
{
    public class LayoutController : Controller
    {

        #region RightBox

        public ActionResult RightBoxXemNhieu()
        {
            //var model = BoFactory.RealEstate.SearchTopView(5) ?? new List<Out_RealEstate_SelectTopView_Result>();
            var model = PstHelper.Real_Search(new RealSearchModel() {
                BuyOrRent = 0,
                PageIndex = 0,
                PageSize = 5,
                SortType = 11
            });
            return PartialView(model);
        }
        public ActionResult RightBoxTinTuc()
        {
            var db = new PstEntities();
            var model = db.Out_Article_GetTopArticle(10, 1).ToList();
            return View(model);
        }

        public ActionResult RightBoxQuan(int cityId = 0, int districtId = 0, int wardId = 0, int saleOrRent = 1)
        {
            if (cityId == 0)
                return Content("");
            ViewBag.cityId = cityId;
            ViewBag.districtId = districtId;
            ViewBag.saleOrRent = saleOrRent;
            var ci = BoFactory.AddressBook.GetCityList().FirstOrDefault(c => c.Id == cityId);
            if (ci != null)
                ViewBag.cityName = ci.CityName;
            var db = new PstEntities();
            var model = db.Out_RealEstate_CountByDistrict(cityId).ToList();
            return View(model.OrderBy(c => {
                if (c.DistrictName.StartsWith("Quận"))
                    return c.DistrictName.CleanNotNumber().ToInt();
                return 1000;
            }).ThenBy(c => c.DistrictName).ToList());
        }

        public ActionResult RightBoxPhuong(int cityId = 0, int districtId = 0, int wardId = 0, int saleOrRent = 1)
        {
            if (districtId == 0 && wardId == 0)
                return Content("");
            ViewBag.cityId = cityId;
            ViewBag.districtId = districtId;
            ViewBag.wardId = wardId;
            ViewBag.saleOrRent = saleOrRent;
            var dis = BoFactory.AddressBook.GetDistrictById(districtId);
            if (dis != null)
                ViewBag.districtName = dis.DistrictName;
            var model = BoFactory.RealEstate.CountByWard(districtId) ?? new List<Out_RealEstate_CountByWard_Result>();
            return View(model.OrderBy(c => {
                if (c.WardName.StartsWith("Phường"))
                    return c.WardName.CleanNotNumber().ToInt();
                return 1000;
            }).ThenBy(c => c.WardName).ToList());
        }
        public ActionResult RightBoxInfo()
        {
            return View();
        }
        #endregion

        #region BoxGiaTot


        public ActionResult BoxGiaTot(int tabIndex = 1)
        {
            var db = new PstEntities();
            ViewBag.model1 = db.Out_Real_SelectTopHot(20, RealBuyOrRentEnum.Buy.Value()).ToList();
            ViewBag.model2 = db.Out_Real_SelectTopHot(20, RealBuyOrRentEnum.Rent.Value()).ToList();
            return View(tabIndex);
        }

        #endregion

        #region ContactStaff

        public ActionResult ContactStaff()
        {
            return View();
        }


        public ActionResult ContactToStaff(int brokerId, int realId)
        {
            var model = new ContactToStaff {
                BrokerId = brokerId,
                RealId = realId
            };
            return PartialView(model);
        }
        public ActionResult ServiceContact()
        {
            var model = new ContactToStaff {
                BrokerId = 0
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult ContactToStaff(ContactToStaff model)
        {
            if (ModelState.IsValid) {
                BoFactory.UserFeedback.Add(new UserFeedback() {
                    CreateDate = DateTime.Now,
                    Mobile = model.Phone,
                    ContactName = model.FullName,
                    Email = model.Email,
                    Feedback = model.Content,
                    BrokerId = model.BrokerId,
                    KeywordS = StringExtension.ConvertToUnSign(string.Concat("#", model.Phone, " #", model.FullName, " #", model.Email)),
                    ProductId = model.RealId
                });
                var gmailSender = new GmailSender {
                    Subject = string.Format("Yêu cầu từ bđs: {0}", model.RealId),
                    Body = string.Format("" +
                                         "Tên: {0}<br/>" +
                                         "Điện thoại: {1}<br/>" +
                                         "Email: {2}<br/>" +
                                         "Nội dung: {3}<br/>" +
                                         "Mã BĐS: {4}<br/>" +
                                         "Thời gian: {5}", model.FullName, model.Phone, model.Email, model.Content, model.RealId,DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"))
                };

                //try {
                gmailSender.Send();
                //}
                //// ReSharper disable once EmptyGeneralCatchClause
                //catch {
                //}
                ViewBag.Success = true;

            }
            return PartialView(model);
        }

        #endregion

        //public ActionResult RenderPaging(int total, int pageSize = 1, int currentPage = 1)
        //{
        //    var model = new PagingModel(total, pageSize, currentPage, 5);
        //    return PartialView(model);
        //}

    }
}

OutsideX/Views/Layout/BoxGiaTot.cshtml
@using MyUtility.Extensions
@using OutsideX.EF
@using OutsideX.Models
@model dynamic
@{
    Layout = null;
    var model1 = ViewBag.model1 as List<Out_Real_SelectTopHot_Result>;
    var model2 = ViewBag.model2 as List<Out_Real_SelectTopHot_Result>;
}
<div class="tab_box box_gia_tot" id="">
    <ul class="nav nav-tabs" role="tablist">
        @{
            var action = "";
            var routeValues = HttpContext.Current.Request.RequestContext.RouteData.Values;
            if (routeValues.ContainsKey("action"))
            {
                action = (string)routeValues["action"];
            }
        }
        @switch (action)
        {
            case "NhaDatBan":
                <li role="presentation" class="active" id="showTop"><a href="#nhadatgiatot" aria-controls="nhadatgiatot" role="tab" data-toggle="tab">MUA BÁN GIÁ TỐT</a></li>
                break;
            case "NhaDatChoThue":
            <li role="presentation" class="active" id="showHot"><a href="#chothuegiatot" aria-controls="chothuegiatot" role="tab" data-toggle="tab">CHO THUÊ GIÁ TỐT</a></li>
                break;
            default:
            <li role="presentation" class="active" id="showTop"><a href="#nhadatgiatot" aria-controls="nhadatgiatot" role="tab" data-toggle="tab">MUA BÁN GIÁ TỐT</a></li>
            <li role="presentation" id="showHot"><a href="#chothuegiatot" aria-controls="chothuegiatot" role="tab" data-toggle="tab">CHO THUÊ GIÁ TỐT</a></li>
                break;
        }

    </ul>

    <div class="tab-content borer_red background-color-white">
        <div role="tabpanel" class="tab-pane @(action != "NhaDatChoThue"?"active":"") " id="nhadatgiatot">
            <div class="box_slider padding-10">
                <ul class="home-slider">
                    @{Html.RenderPartial("_ListPriceHotItem", PstHelper.ConvertToRealSearchModel(model1));}
                </ul>
                <div class=" text-align-right">
                    <a title="Xem thêm" href="@Url.Action("NhaDatGiaTot", "RealEstate", new {  })">Xem thêm...</a>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane @(action == "NhaDatChoThue"?"active":"")" id="chothuegiatot">
            <div class="box_slider padding-10">
                @if (model2 != null && model2.Any())
                {
                    <ul class="home-slider">
                        @{Html.RenderPartial("_ListPriceHotItem", PstHelper.ConvertToRealSearchModel(model2));}
                    </ul>


                    <div class=" text-align-right">
                        <a title="Xem thêm" href="@Url.Action("ChoThueGiaTot", "RealEstate", new {choThue = true})">Xem thêm...</a>
                    </div>
                }
                else
                {
                    @*<div class="alert alert-warning"></div>*@
                }
            </div>
        </div>
    </div>
</div>

OutsideX/Views/Layout/ContactStaff.cshtml
@model OutsideX.Models.ContactToStaff
@{
    Layout = null;
}


<div class="background-color-white margin-top-20">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-sm-4 padding-right-0">
                    <div class="padding-15">
                        <img src="~/Content/img/ico-user.png" class="width-100">
                    </div>
                </div>
                <div class="col-sm-8 padding-left-0 padding-top-15">
                    <div><strong class="font-size-18 color-014b8a">MINH QUÂN</strong></div>
                    <div>Đã xác thực CMND</div>
                    <div><img src="~/Content/img/ico-phone.png"> <span class="font-size-18 color-ed1c24 bold">0909 077 247</span></div>
                    Để hỏi về BĐS này, vui lòng nhập thông tin và câu hỏi của bạn:
                </div>
            </div>
        </div>
        <div class="col-md-6">
            @{Html.RenderAction("ContactToStaff");}
        </div>
    </div>
</div>

OutsideX/Views/Layout/ContactToStaff.cshtml
@model OutsideX.Models.ContactToStaff
@{
    Layout = null;
}
@if (ViewBag.Success == true) {
    <br />
    <div class="padding-20">
        <div class="alert alert-success text-align-center">Xin cám ơn bạn đã liên hệ. Chúng tôi sẽ gọi lại theo số điện thoại bạn đã đăng ký trong thời gian sớm nhất.</div>
    </div>
}
else {
    <div id="">
        @using (Ajax.BeginForm("ContactToStaff", "Layout", new AjaxOptions {//GetPatients is name of method in PatientController
            InsertionMode = InsertionMode.Replace, //target element(#patientList) will be replaced
            UpdateTargetId = "patientList",
            //LoadingElementId = "loader" // div with .gif loader - that is shown when data are loading
        })) {
            <div class="padding-15">
                <div class="maxwidth-640">

                    <div class="form-group">
                        @Html.TextBoxFor(c => c.FullName, new { type = "", @class = "form-control border-radius-0", placeholder = "Họ tên..." })
                        @Html.ValidationMessageFor(c => c.FullName)
                        @Html.HiddenFor(c => c.BrokerId)
                        @Html.HiddenFor(c => c.RealId)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(c => c.Phone, new { type = "", @class = "form-control border-radius-0", placeholder = "Số điện thoại..." })
                        @Html.ValidationMessageFor(c => c.Phone)


                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(c => c.Email, new { type = "email", @class = "form-control border-radius-0", placeholder = "Email..." })
                        @Html.ValidationMessageFor(c => c.Email)
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(c => c.Content, new { @class = "form-control border-radius-0", placeholder = "Nhu cầu của bạn...", rows = "4" })
                        @Html.ValidationMessageFor(c => c.Content)
                    </div>
                    <div>
                        <!--<button type="submit" class="btn btn-default background-color-0e5490 color-white border-radius-4 border-none">Gửi Thư</button>-->
                        <button type="submit" class="btn btn-primary">Gửi Thư</button>
                    </div>
                </div>
            </div>
        }
    </div>
}

OutsideX/Views/Layout/RightBoxInfo.cshtml
@{
    Layout = null;
}
<div class="right_box_info">
    <div class="name">
        <img src="~/Content/img/phu-sai-thanh.png" class="img-responsive">
    </div>
    <div class="address">334 Chợ Lớn, P.11, Q.6, TP.HCM</div>
    <a href="mailto:phusaithanh.pst@gmail.com">
        <div class="email">phusaithanh.pst@gmail.com</div>
    </a>
</div>

OutsideX/Views/Layout/RightBoxPhuong.cshtml
@model List<EntitiesObject.Entities.WebEntities.Out_RealEstate_CountByWard_Result>
@{
    Layout = null;
     //ViewBag.districtId = districtId;
     //       ViewBag.wardId = wardId;
}
<div class="right_box_4 padding-left-10 padding-right-10">
    <div class="right_box_title">
        <label class="r-icon2">NHÀ ĐẤT BÁN TẠI @ViewBag.districtName</label>
    </div>
    <div class="div_right_line2"></div>
    <div class="right_box_content padding-top-10 padding-bottom-10 color-black">
        @foreach (var item in Model)
        {
            <div class="margin-bottom-5">
                <a href="@Url.Action("Index", "Search", new { cityId = ViewBag.cityId, districtId = ViewBag.districtId, wardId = item.WardId, SaleOrRent = ViewBag.saleOrRent })" class="@(item.WardId == ViewBag.wardId ? "color-ed1c24" : "")">
                    <span class="glyphicon glyphicon-play-circle margin-right-5 "></span>@item.WardName (@item.TotalProduct)
                </a>
            </div>
        }
    </div>
</div>

OutsideX/Views/Layout/RightBoxQuan.cshtml
@model List<OutsideX.EF.Out_RealEstate_CountByDistrict_Result>
@{
    Layout = null;
     //ViewBag.districtId = districtId;
     //       ViewBag.wardId = wardId;
}
<div class="right_box_4 padding-left-10 padding-right-10">
    <div class="right_box_title">
        <label class="r-icon2">NHÀ ĐẤT @ViewBag.cityName</label>
    </div>
    <div class="div_right_line2"></div>
    <div class="right_box_content padding-top-10 padding-bottom-10 color-black">
        @foreach (var item in Model)
        {
            <div class="margin-bottom-5">
                <a href="@Url.Action("Index", "Search", new { cityId = ViewBag.cityId, districtId = item.DistrictId, SaleOrRent = ViewBag.saleOrRent })" class="@(item.DistrictId == ViewBag.districtId ? "color-ed1c24" : "")">
                    <span class="glyphicon glyphicon-play-circle margin-right-5 "></span>@item.DistrictName (@item.TotalProduct)
                </a>
            </div>
        }
    </div>
</div>

OutsideX/Views/Layout/RightBoxTinTuc.cshtml
@using OutsideX.Models
@using PhuSaiThanhLib
@model List<OutsideX.EF.Out_Article_GetTopArticle_Result>
@{
    Layout = null;
}
@if (Model != null)
{
    <div class="right_box_3">
        <div class="right_box_title">
            <label class="r-icon2">TIN TỨC</label>
        </div>
        <div class="div_right_line2"></div>
        <br />
        <div class="right_box_content">
            @foreach (var item in Model)
            {
                <div class="media">
                    <div class="media-left">
                        <a class="item_link_right_hover" href="@Url.Action("Detail", "News", new { id = item.ID })" title="@Html.Raw(item.Title)">
                            <img class="media-object" src="@(string.IsNullOrEmpty(item.Avatar) ? BasicHelper.DefaultImage : item.Avatar.GetFullUrlImage())" width="64" height="64" alt="@Html.Raw(item.Title)">
                        </a>
                    </div>
                    <div class="media-body">
                        <a href="@Url.Action("Detail", "News", new { id = item.ID })" title="@item.Title">
                            <div class="font-size-15 media-heading">
                                @Html.Raw(item.Title.MaxLength(70))
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
    <br/>
    <br/>
}

OutsideX/Views/Layout/RightBoxXemNhieu.cshtml
@using MyUtility.Extensions
@using OutsideX.Models
@using PhuSaiThanhLib
@model List<OutsideX.EF.Out_Real_Search_Result>
@{
    Layout = null;
}
@if (Model != null)
{
    <div class="right_box_3">
        <div class="right_box_title">
            <label class="r-icon2">XEM NHIỀU NHẤT</label>
        </div>
        <div class="div_right_line2"></div>
        <br />
        <div class="right_box_content">
            @foreach (var item in Model)
            {
                @*<div class="r_bottom_line">
                        <a class="item_link_right_hover" href="@Url.Action("DetailCustomer", "RealEstate", new { id = item.Id, productId = item.ProductId })">• @Html.Raw(item.ProductName)</a>
                    </div>*@
                <div class="media">
                    <div class="media-left">
                        <a class="item_link_right_hover" href="@Url.Action("DetailCustomer", "RealEstate", new { id = item.Id})" title="@item.Title">
                            <img class="media-object" src="@item.Hinh.GetFullUrlImage()" width="64" height="64" alt="...">
                        </a>
                    </div>
                    <div class="media-body">
                        <a href="@Url.Action("DetailCustomer", "RealEstate", new { id = item.Id})" title="@item.Title">

                            <div class="font-size-15 media-heading">
                                @Html.Raw(item.Title.MaxLength(35))
                                <div class="">
                                    @Html.Raw(item.Price.DecimalToText(""))
                                    <span class='color-ed1c24'><span class='font-size-16'><strong>@item.Price.DecimalFormat("0") </strong></span><span class='font-size-14'>@(item.BuyOrRent.ToUnitBuyOrRent())</span></span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>

}

OutsideX/Views/Layout/ServiceContact.cshtml
@model OutsideX.Models.ContactToStaff
@{
    Layout = null;
}
@if (ViewBag.Success == true)
{
    <br />
    <div class="padding-20">
        <div class="alert alert-success text-align-center">
            Để được tư vấn thông tin chi tiết, vui lòng nhập thông tin và yêu cầu của bạn
        </div>
    </div>
}
else
{
    <div id="">
        @using (Ajax.BeginForm("ContactToStaff", "Layout", new AjaxOptions
        {//GetPatients is name of method in PatientController
            InsertionMode = InsertionMode.Replace, //target element(#patientList) will be replaced
            UpdateTargetId = "patientList",
            //LoadingElementId = "loader" // div with .gif loader - that is shown when data are loading
        }))
        {
            <div class="padding-15">
                <div class="maxwidth-640">

                    <div class="form-group">
                        @Html.TextBoxFor(c => c.FullName, new { type = "", @class = "form-control border-radius-0", placeholder = "Họ tên..." })
                        @Html.ValidationMessageFor(c => c.FullName)
                        @Html.HiddenFor(c => c.BrokerId)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(c => c.Phone, new { type = "", @class = "form-control border-radius-0", placeholder = "Số điện thoại..." })
                        @Html.ValidationMessageFor(c => c.Phone)


                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(c => c.Email, new { type = "email", @class = "form-control border-radius-0", placeholder = "Email..." })
                        @Html.ValidationMessageFor(c => c.Email)
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(c => c.Content, new { @class = "form-control border-radius-0", placeholder = "Yêu cầu của bạn...", rows = "4" })
                        @Html.ValidationMessageFor(c => c.Content)
                    </div>
                    <div>
                        <!--<button type="submit" class="btn btn-default background-color-0e5490 color-white border-radius-4 border-none">Gửi Thư</button>-->
                        <button type="submit" class="btn btn-primary">Gửi Thư</button>
                    </div>
                </div>
            </div>
        }
    </div>
}